name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1
        with:
          channel: master
      - run: flutter doctor -v

      - name: Install Dependencies
        run: flutter pub get -v
        working-directory: .

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze lib test example
        
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
        
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with: 
         token: ${{ secrets.CODECOV_TOKEN }} 
         file: coverage/lcov.info
